server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        enabled: true    #开启从注册中心到动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh    #payment_route 路由的Id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由
        - id: payment_routh2       #p 路由的Id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**      #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

