server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  instance:
    prefer-ip-address: true

    #eureka等待上限

  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/