server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
spring:
  application:
    name: cloud-consumer-order
  zipkin:
    base-url: http://127.0.0.1:9411
    sleuth:
      sampler:   #1全部采集  0到一之间
        probability: 1

#ribbon:
  #ReadTimeout: 5000
  #ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeign: debug
